### ISSUE TITLE
On Macbook Pro when use atom-preview enhanced , the MathJax can 't render out fine.

### ISSUE THREAD

**Issue by davidzhong123** [shd101wyy/markdown-preview-enhanced#785] opened 2018-02-12 04:03 UTC
the $$ or $ transfered to undefined.

**Comment by iove1123** [comment] 2018-02-12 04:07
<img width="1395" alt="2018-02-12 12 05 28" src="https://user-images.githubusercontent.com/18346105/36083455-533882f6-0fed-11e8-9d92-b14dd38b3377.png">

**Comment by iove1123** [comment] 2018-02-12 04:08
when in windows7， the same code works perfect.

**Comment by sheljohn** [comment] 2018-02-13 12:18
Duplicate of #775 ?

**Comment by iove1123** [comment] 2018-02-20 15:26
<img width="1127" alt="2018-02-20 23 21 27" src="https://user-images.githubusercontent.com/18346105/36432351-f69a05d4-1694-11e8-935e-11001a811f5d.png">
It seems the markdown-preview-enhanced can not translate the mathJax properly, unless there is a <p> tag before the math expression. @sheljohn @shd101wyy

**Closed** 2018-03-03 12:17 UTC
