### ISSUE TITLE
Always "Welcome to PlantUML" message shown.

### ISSUE THREAD

**Issue by tmori3y2** [shd101wyy/markdown-preview-enhanced#398] opened 2017-05-08 23:43 UTC
.atom\packages\markdown-preview-enhanced\dependencies\plantuml\plantuml.jar
was updated from 8054 to 1.2017.12.

Then always "Welcome to PlantUML" message shown.

I don't know how to clear this message except to overwrite it by the old version, 8059 or earlier, downloaded from https://sourceforge.net/projects/plantuml/files/old/.

Best regards.

<img width="392" alt="welcome to plantuml" src="https://cloud.githubusercontent.com/assets/18054170/25829860/fff7d716-3493-11e7-9987-8ab056552461.PNG">

**Comment by shd101wyy** [comment] 2017-05-08 23:57
@tmori3y2 Oh I didn't meet this issue.  
Maybe you should upgrade your Java?

**Comment by shd101wyy** [comment] 2017-05-08 23:59
@tmori3y2 maybe [this issue](https://github.com/plantuml/plantuml/issues/25) is related.

**Comment by tmori3y2** [comment] 2017-05-09 01:38
I tried the additional test.

If you use the import directive, then this message is shown at end of diagram.

# testuml.md is here.

# Test UML

// code block (puml)
```puml
@startuml

class A
class B

A -> B

@enduml
```

// code block (@puml)
```@puml
@startuml

class A
class B

A -> B

@enduml
```


// @import "testuml.puml"
```puml
@startuml

class A
class B

A -> B

@enduml
```

@import "testuml.puml"


# Captured preview

![testuml](https://cloud.githubusercontent.com/assets/18054170/25832086/6089cd46-34a3-11e7-80a3-9e5fc737f29a.png)

**Comment by tmori3y2** [comment] 2017-05-09 01:42
PlantUML version 1.2017.12 (Thu Apr 27 01:06:36 JST 2017)
(GPL source distribution)
Java Runtime: Java(TM) SE Runtime Environment
JVM: Java HotSpot(TM) Client VM
Java Version: 1.7.0_21-b11
Operating System: Windows 7
OS Version: 6.1
Default Encoding: MS932
Language: ja
Country: JP
Machine: EA9118
PLANTUML_LIMIT_SIZE: 4096
Processors: 8
Max Memory: 259,522,560
Total Memory: 16,252,928
Free Memory: 14,296,592
Used Memory: 1,956,336
Thread Active Count: 1

The environment variable GRAPHVIZ_DOT has been set to c:\Program Files (x86)\Gra
phviz2.38\bin\dot.exe
Dot executable is c:\Program Files (x86)\Graphviz2.38\bin\dot.exe
Dot version: dot - graphviz version 2.38.0 (20140413.2041)
Installation seems OK. File generation OK

**Comment by shd101wyy** [comment] 2017-05-09 01:43
![screen shot 2017-05-08 at 8 42 27 pm](https://cloud.githubusercontent.com/assets/1908863/25832215/e6b35ff6-342e-11e7-8204-d4fbd92a4dd1.png)
Dunno why but I will try to fix it.

**Comment by shd101wyy** [comment] 2017-05-09 01:48
Oh I also met the `@import` issue. I will have a look about it when I am free.

**Comment by shd101wyy** [comment] 2017-05-09 01:51
Oh I see where is wrong.  
[this line](https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/lib/puml.coffee#L14) appends extra `@startuml`.

**Comment by tmori3y2** [comment] 2017-05-09 01:52
Additional Information:

I also met this issue when using 1.2017.8 and 1.2017.11.

Best Regards.

**Comment by shd101wyy** [comment] 2017-05-09 03:15
@tmori3y2 should be fixed now :)

**Comment by tmori3y2** [comment] 2017-05-09 03:28
Good job !

**Closed** 2017-05-09 04:45 UTC

**Comment by veponen** [comment] 2018-01-03 20:05
I have same kind of behaviour experience. Always the "Welcome to plantuml" message only. This is related to Gollum though. So currently I am learning Ruby to find out how to get it working... When I run the plantuml service as a local web service with Jetty it works fine. But when I try to combine it to Gollum it fails miserably.... Will be debuggin that, possibly Gollum configuration issue, but just can not find the root cause. Using the latest Gollum and PlantUML.
